const configData = {
  "minimumOrderQuantity": 5,
  "materials": [
    { "id": "mat-1", "label": "Eyelet 165GSM (BEST SELLER)", "price": 0 },
    { "id": "mat-2", "label": "Mini Eyelet 165GSM", "price": 0 },
    { "id": "mat-3", "label": "Interlock 160GSM", "price": 0 },
    { "id": "mat-4", "label": "Diamond 160GSM", "price": 3 },
    { "id": "mat-5", "label": "RJPK 180GSM", "price": 3 },
    { "id": "mat-6", "label": "Cotton Feel 165GSM", "price": 6 },
    { "id": "mat-7", "label": "Diamond V2 180GSM", "price": 6 },
    { "id": "mat-8", "label": "Jacquard 145GSM", "price": 6 },
    { "id": "mat-9", "label": "Micro Lattice 140GSM", "price": 6 },
    { "id": "mat-10", "label": "PK 160GSM", "price": 6 },
    { "id": "mat-11", "label": "Popcorn 160GSM", "price": 6 },
    { "id": "mat-12", "label": "PU Diamond 155GSM", "price": 6 },
    { "id": "mat-13", "label": "Tricot 200GSM", "price": 6 },
    { "id": "mat-14", "label": "Vertical Zigzag 180GSM", "price": 6 },
    { "id": "mat-15", "label": "Waffle 155GSM", "price": 6 },
    { "id": "mat-16", "label": "Baseball 230GSM", "price": 8 },
    { "id": "mat-17", "label": "Cloud 175GSM", "price": 8 },
    { "id": "mat-18", "label": "Contour 165GSM", "price": 8 },
    { "id": "mat-19", "label": "Planet 155GSM", "price": 8 },
    { "id": "mat-20", "label": "Square 155GSM", "price": 8 },
    { "id": "mat-21", "label": "Wire 165GSM", "price": 8 }
  ],
  "cuttings": [
    { "id": "cut-1", "label": "Normal Cutting", "price": 0 },
    { "id": "cut-2", "label": "Raglan Cutting", "price": 4 },
    { "id": "cut-3", "label": "Baseball Cutting", "price": 5 },
    { "id": "cut-4", "label": "Boxy Cutting", "price": 5 },
    { "id": "cut-5", "label": "Singlet Cutting", "price": 5 },
    { "id": "cut-6", "label": "Sleeveless Cutting", "price": 5 }
  ],
  "sleeves": [
    { "id": "slv-1", "label": "Short Sleeve", "price": 0 },
    { "id": "slv-2", "label": "Long Sleeve", "price": 5 }
  ],
  "necks": [
    { "id": "nck-1", "label": "Roundneck", "price": 0 },
    { "id": "nck-2", "label": "V-neck", "price": 3 },
    { "id": "nck-3", "label": "V-neck Cross", "price": 3 },
    { "id": "nck-4", "label": "V-neck End", "price": 3 },
    { "id": "nck-5", "label": "Henly Stub", "price": 5 },
    { "id": "nck-6", "label": "Collar 1 Button", "price": 6 },
    { "id": "nck-7", "label": "Collar 2 Button", "price": 6 },
    { "id": "nck-8", "label": "Collar Button (Polo)", "price": 6 },
    { "id": "nck-9", "label": "Collar No Button", "price": 6 },
    { "id": "nck-10", "label": "Collar Zip", "price": 6 },
    { "id": "nck-11", "label": "Mandarin Collar", "price": 6 },
    { "id": "nck-12", "label": "Mandarin Hidden Button", "price": 6 },
    { "id": "nck-13", "label": "Mandarin Zip", "price": 6 },
    { "id": "nck-14", "label": "Retro Cross", "price": 6 },
    { "id": "nck-15", "label": "Retro End", "price": 6 },
    { "id": "nck-16", "label": "Retro No Insert", "price": 6 },
    { "id": "nck-17", "label": "Retro V-line", "price": 6 },
    { "id": "nck-18", "label": "RetroCollar", "price": 6 },
    { "id": "nck-19", "label": "Roundneck 2 Button", "price": 6 },
    { "id": "nck-20", "label": "Roundneck Cross", "price": 6 },
    { "id": "nck-21", "label": "Roundneck Stub", "price": 6 },
    { "id": "nck-22", "label": "Roundneck Zip", "price": 6 },
    { "id": "nck-23", "label": "Collar Barbos", "price": 7 },
    { "id": "nck-24", "label": "Collar Loop", "price": 7 },
    { "id": "nck-25", "label": "V-neck Outer", "price": 7 },
    { "id": "nck-26", "label": "V-neck Outer End", "price": 7 },
    { "id": "nck-27", "label": "V-loop Insert", "price": 11 },
    { "id": "nck-28", "label": "V-neck Diamond Outer", "price": 11 },
    { "id": "nck-29", "label": "V-neck Double Layer (New)", "price": 11 }
  ]
}
